"""initial schema 11 tables v2

Revision ID: c3c01b64fb39
Revises: a1cb1c39627a
Create Date: 2026-04-06 14:21:12.395031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3c01b64fb39'
down_revision: Union[str, Sequence[str], None] = 'a1cb1c39627a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('district_sales',
    sa.Column('quarter', sa.Integer(), nullable=False, comment='기준 분기 (YYYYQ)'),
    sa.Column('dong_code', sa.String(length=10), nullable=False, comment='행정동 코드'),
    sa.Column('industry_code', sa.String(length=20), nullable=False, comment='업종 코드'),
    sa.Column('dong_name', sa.String(length=20), nullable=True, comment='행정동명'),
    sa.Column('industry_name', sa.String(length=50), nullable=True, comment='업종명'),
    sa.Column('monthly_sales', sa.BigInteger(), nullable=True, comment='월 매출 금액'),
    sa.Column('monthly_count', sa.Integer(), nullable=True, comment='월 매출 건수'),
    sa.Column('weekday_sales', sa.BigInteger(), nullable=True, comment='평일 매출 금액'),
    sa.Column('weekend_sales', sa.BigInteger(), nullable=True, comment='주말 매출 금액'),
    sa.Column('mon_sales', sa.BigInteger(), nullable=True, comment='월요일 매출 금액'),
    sa.Column('tue_sales', sa.BigInteger(), nullable=True, comment='화요일 매출 금액'),
    sa.Column('wed_sales', sa.BigInteger(), nullable=True, comment='수요일 매출 금액'),
    sa.Column('thu_sales', sa.BigInteger(), nullable=True, comment='목요일 매출 금액'),
    sa.Column('fri_sales', sa.BigInteger(), nullable=True, comment='금요일 매출 금액'),
    sa.Column('sat_sales', sa.BigInteger(), nullable=True, comment='토요일 매출 금액'),
    sa.Column('sun_sales', sa.BigInteger(), nullable=True, comment='일요일 매출 금액'),
    sa.Column('time_00_06_sales', sa.BigInteger(), nullable=True, comment='00~06시 매출 금액'),
    sa.Column('time_06_11_sales', sa.BigInteger(), nullable=True, comment='06~11시 매출 금액'),
    sa.Column('time_11_14_sales', sa.BigInteger(), nullable=True, comment='11~14시 매출 금액'),
    sa.Column('time_14_17_sales', sa.BigInteger(), nullable=True, comment='14~17시 매출 금액'),
    sa.Column('time_17_21_sales', sa.BigInteger(), nullable=True, comment='17~21시 매출 금액'),
    sa.Column('time_21_24_sales', sa.BigInteger(), nullable=True, comment='21~24시 매출 금액'),
    sa.Column('male_sales', sa.BigInteger(), nullable=True, comment='남성 매출 금액'),
    sa.Column('female_sales', sa.BigInteger(), nullable=True, comment='여성 매출 금액'),
    sa.Column('age_10_sales', sa.BigInteger(), nullable=True, comment='10대 매출 금액'),
    sa.Column('age_20_sales', sa.BigInteger(), nullable=True, comment='20대 매출 금액'),
    sa.Column('age_30_sales', sa.BigInteger(), nullable=True, comment='30대 매출 금액'),
    sa.Column('age_40_sales', sa.BigInteger(), nullable=True, comment='40대 매출 금액'),
    sa.Column('age_50_sales', sa.BigInteger(), nullable=True, comment='50대 매출 금액'),
    sa.Column('age_60_above_sales', sa.BigInteger(), nullable=True, comment='60대 이상 매출 금액'),
    sa.Column('weekday_count', sa.Integer(), nullable=True, comment='평일 매출 건수'),
    sa.Column('weekend_count', sa.Integer(), nullable=True, comment='주말 매출 건수'),
    sa.Column('mon_count', sa.Integer(), nullable=True, comment='월요일 매출 건수'),
    sa.Column('tue_count', sa.Integer(), nullable=True, comment='화요일 매출 건수'),
    sa.Column('wed_count', sa.Integer(), nullable=True, comment='수요일 매출 건수'),
    sa.Column('thu_count', sa.Integer(), nullable=True, comment='목요일 매출 건수'),
    sa.Column('fri_count', sa.Integer(), nullable=True, comment='금요일 매출 건수'),
    sa.Column('sat_count', sa.Integer(), nullable=True, comment='토요일 매출 건수'),
    sa.Column('sun_count', sa.Integer(), nullable=True, comment='일요일 매출 건수'),
    sa.Column('time_00_06_count', sa.Integer(), nullable=True, comment='00~06시 매출 건수'),
    sa.Column('time_06_11_count', sa.Integer(), nullable=True, comment='06~11시 매출 건수'),
    sa.Column('time_11_14_count', sa.Integer(), nullable=True, comment='11~14시 매출 건수'),
    sa.Column('time_14_17_count', sa.Integer(), nullable=True, comment='14~17시 매출 건수'),
    sa.Column('time_17_21_count', sa.Integer(), nullable=True, comment='17~21시 매출 건수'),
    sa.Column('time_21_24_count', sa.Integer(), nullable=True, comment='21~24시 매출 건수'),
    sa.Column('male_count', sa.Integer(), nullable=True, comment='남성 매출 건수'),
    sa.Column('female_count', sa.Integer(), nullable=True, comment='여성 매출 건수'),
    sa.Column('age_10_count', sa.Integer(), nullable=True, comment='10대 매출 건수'),
    sa.Column('age_20_count', sa.Integer(), nullable=True, comment='20대 매출 건수'),
    sa.Column('age_30_count', sa.Integer(), nullable=True, comment='30대 매출 건수'),
    sa.Column('age_40_count', sa.Integer(), nullable=True, comment='40대 매출 건수'),
    sa.Column('age_50_count', sa.Integer(), nullable=True, comment='50대 매출 건수'),
    sa.Column('age_60_above_count', sa.Integer(), nullable=True, comment='60대 이상 매출 건수'),
    sa.PrimaryKeyConstraint('quarter', 'dong_code', 'industry_code')
    )
    op.create_index(op.f('ix_district_sales_dong_code'), 'district_sales', ['dong_code'], unique=False)
    op.create_table('dong_mapping',
    sa.Column('dong_code', sa.String(length=10), nullable=False, comment='행정동 코드'),
    sa.Column('dong_name', sa.String(length=20), nullable=True, comment='행정동명'),
    sa.Column('resident_pop', sa.Integer(), nullable=True, comment='주민등록 인구'),
    sa.Column('floating_pop', sa.Float(), nullable=True, comment='유동인구'),
    sa.Column('avg_age', sa.Float(), nullable=True, comment='평균 연령'),
    sa.Column('total_households', sa.Integer(), nullable=True, comment='총 가구 수'),
    sa.Column('trdar_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='상권 코드 목록 (JSON 배열)'),
    sa.PrimaryKeyConstraint('dong_code')
    )
    op.create_table('golmok_commercial',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='자동증가 PK'),
    sa.Column('quarter', sa.Integer(), nullable=True, comment='기준 분기 (YYYYQ)'),
    sa.Column('trdar_code', sa.String(length=10), nullable=True, comment='상권 코드'),
    sa.Column('data_type', sa.String(length=20), nullable=True, comment='데이터 유형 (sales/store/population 등)'),
    sa.Column('industry_code', sa.String(length=20), nullable=True, comment='업종 코드 (기본값: ALL)'),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='지표 데이터 (JSON)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_golmok_commercial_data_type'), 'golmok_commercial', ['data_type'], unique=False)
    op.create_index(op.f('ix_golmok_commercial_quarter'), 'golmok_commercial', ['quarter'], unique=False)
    op.create_table('living_population',
    sa.Column('date', sa.Date(), nullable=False, comment='기준 날짜'),
    sa.Column('time_zone', sa.SmallInteger(), nullable=False, comment='시간대 구분 (0~23)'),
    sa.Column('dong_code', sa.String(length=10), nullable=False, comment='행정동 코드'),
    sa.Column('dong_name', sa.String(length=20), nullable=True, comment='행정동명'),
    sa.Column('total_pop', sa.Float(), nullable=True, comment='전체 생활인구'),
    sa.Column('male_0_9', sa.Float(), nullable=True, comment='남성 0~9세'),
    sa.Column('male_10_14', sa.Float(), nullable=True, comment='남성 10~14세'),
    sa.Column('male_15_19', sa.Float(), nullable=True, comment='남성 15~19세'),
    sa.Column('male_20_24', sa.Float(), nullable=True, comment='남성 20~24세'),
    sa.Column('male_25_29', sa.Float(), nullable=True, comment='남성 25~29세'),
    sa.Column('male_30_34', sa.Float(), nullable=True, comment='남성 30~34세'),
    sa.Column('male_35_39', sa.Float(), nullable=True, comment='남성 35~39세'),
    sa.Column('male_40_44', sa.Float(), nullable=True, comment='남성 40~44세'),
    sa.Column('male_45_49', sa.Float(), nullable=True, comment='남성 45~49세'),
    sa.Column('male_50_54', sa.Float(), nullable=True, comment='남성 50~54세'),
    sa.Column('male_55_59', sa.Float(), nullable=True, comment='남성 55~59세'),
    sa.Column('male_60_64', sa.Float(), nullable=True, comment='남성 60~64세'),
    sa.Column('male_65_69', sa.Float(), nullable=True, comment='남성 65~69세'),
    sa.Column('male_70_74', sa.Float(), nullable=True, comment='남성 70~74세'),
    sa.Column('male_70_plus', sa.Float(), nullable=True, comment='남성 70세 이상'),
    sa.Column('female_0_9', sa.Float(), nullable=True, comment='여성 0~9세'),
    sa.Column('female_10_14', sa.Float(), nullable=True, comment='여성 10~14세'),
    sa.Column('female_15_19', sa.Float(), nullable=True, comment='여성 15~19세'),
    sa.Column('female_20_24', sa.Float(), nullable=True, comment='여성 20~24세'),
    sa.Column('female_25_29', sa.Float(), nullable=True, comment='여성 25~29세'),
    sa.Column('female_30_34', sa.Float(), nullable=True, comment='여성 30~34세'),
    sa.Column('female_35_39', sa.Float(), nullable=True, comment='여성 35~39세'),
    sa.Column('female_40_44', sa.Float(), nullable=True, comment='여성 40~44세'),
    sa.Column('female_45_49', sa.Float(), nullable=True, comment='여성 45~49세'),
    sa.Column('female_50_54', sa.Float(), nullable=True, comment='여성 50~54세'),
    sa.Column('female_55_59', sa.Float(), nullable=True, comment='여성 55~59세'),
    sa.Column('female_60_64', sa.Float(), nullable=True, comment='여성 60~64세'),
    sa.Column('female_65_69', sa.Float(), nullable=True, comment='여성 65~69세'),
    sa.Column('female_70_74', sa.Float(), nullable=True, comment='여성 70~74세'),
    sa.Column('female_70_plus', sa.Float(), nullable=True, comment='여성 70세 이상'),
    sa.PrimaryKeyConstraint('date', 'time_zone', 'dong_code')
    )
    op.create_table('rent_cost',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='자동증가 PK'),
    sa.Column('data_type', sa.String(length=20), nullable=True, comment='데이터 유형 (rent/transaction)'),
    sa.Column('area_name', sa.String(length=50), nullable=True, comment='지역명'),
    sa.Column('year', sa.SmallInteger(), nullable=True, comment='기준 연도'),
    sa.Column('quarter', sa.SmallInteger(), nullable=True, comment='기준 분기'),
    sa.Column('rent', sa.Float(), nullable=True, comment='임대료 (만원/m²)'),
    sa.Column('vacancy_rate', sa.Float(), nullable=True, comment='공실률'),
    sa.Column('investment_return', sa.Float(), nullable=True, comment='투자 수익률'),
    sa.Column('income_return', sa.Float(), nullable=True, comment='소득 수익률'),
    sa.Column('capital_return', sa.Float(), nullable=True, comment='자본 수익률'),
    sa.Column('transaction_date', sa.String(length=10), nullable=True, comment='거래 일자 (YYYY-MM-DD)'),
    sa.Column('price', sa.BigInteger(), nullable=True, comment='거래 금액 (만원)'),
    sa.Column('floor_area', sa.Float(), nullable=True, comment='전용 면적 (m²)'),
    sa.Column('floor', sa.String(length=10), nullable=True, comment='층 정보'),
    sa.Column('source', sa.String(length=20), nullable=True, comment='데이터 출처'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rent_cost_data_type'), 'rent_cost', ['data_type'], unique=False)
    op.create_table('sgis_business',
    sa.Column('year', sa.SmallInteger(), nullable=False, comment='기준 연도'),
    sa.Column('area_code', sa.String(length=14), nullable=False, comment='행정구역 코드'),
    sa.Column('indicator', sa.String(length=30), nullable=False, comment='지표명'),
    sa.Column('value', sa.Float(), nullable=True, comment='지표 값'),
    sa.PrimaryKeyConstraint('year', 'area_code', 'indicator')
    )
    op.create_table('sgis_household',
    sa.Column('year', sa.SmallInteger(), nullable=False, comment='기준 연도'),
    sa.Column('area_code', sa.String(length=14), nullable=False, comment='행정구역 코드'),
    sa.Column('indicator', sa.String(length=30), nullable=False, comment='지표명'),
    sa.Column('value', sa.Float(), nullable=True, comment='지표 값'),
    sa.PrimaryKeyConstraint('year', 'area_code', 'indicator')
    )
    op.create_table('sgis_population',
    sa.Column('year', sa.SmallInteger(), nullable=False, comment='기준 연도'),
    sa.Column('area_code', sa.String(length=14), nullable=False, comment='행정구역 코드'),
    sa.Column('indicator', sa.String(length=30), nullable=False, comment='지표명'),
    sa.Column('value', sa.Float(), nullable=True, comment='지표 값'),
    sa.PrimaryKeyConstraint('year', 'area_code', 'indicator')
    )
    op.create_table('simulation_result',
    sa.Column('request_id', sa.UUID(), nullable=False, comment='요청 고유 ID (UUID v4)'),
    sa.Column('created_at', sa.Date(), server_default=sa.text('now()'), nullable=True, comment='요청 생성 일시'),
    sa.Column('input_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='시뮬레이션 입력 파라미터 (JSON)'),
    sa.Column('output_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='시뮬레이션 분석 결과 (JSON)'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='처리 상태 (pending/running/done/error)'),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('store_info',
    sa.Column('store_id', sa.String(length=20), nullable=False, comment='점포 고유 ID'),
    sa.Column('store_name', sa.String(length=100), nullable=True, comment='점포명'),
    sa.Column('dong_code', sa.String(length=10), nullable=True, comment='행정동 코드'),
    sa.Column('dong_name', sa.String(length=20), nullable=True, comment='행정동명'),
    sa.Column('address', sa.Text(), nullable=True, comment='지번 주소'),
    sa.Column('road_address', sa.Text(), nullable=True, comment='도로명 주소'),
    sa.Column('lat', sa.Float(), nullable=True, comment='위도'),
    sa.Column('lon', sa.Float(), nullable=True, comment='경도'),
    sa.Column('industry_l_code', sa.String(length=20), nullable=True, comment='대분류 업종 코드'),
    sa.Column('industry_l', sa.String(length=50), nullable=True, comment='대분류 업종명'),
    sa.Column('industry_m_code', sa.String(length=20), nullable=True, comment='중분류 업종 코드'),
    sa.Column('industry_m', sa.String(length=50), nullable=True, comment='중분류 업종명'),
    sa.Column('industry_s_code', sa.String(length=20), nullable=True, comment='소분류 업종 코드'),
    sa.Column('industry_s', sa.String(length=50), nullable=True, comment='소분류 업종명'),
    sa.Column('building_name', sa.String(length=100), nullable=True, comment='건물명'),
    sa.Column('floor_info', sa.String(length=20), nullable=True, comment='층 정보'),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_index(op.f('ix_store_info_dong_code'), 'store_info', ['dong_code'], unique=False)
    op.create_index(op.f('ix_store_info_dong_name'), 'store_info', ['dong_name'], unique=False)
    op.create_index(op.f('ix_store_info_industry_m'), 'store_info', ['industry_m'], unique=False)
    op.create_index(op.f('ix_store_info_industry_m_code'), 'store_info', ['industry_m_code'], unique=False)
    op.create_table('store_quarterly',
    sa.Column('quarter', sa.Integer(), nullable=False, comment='기준 분기 (YYYYQ)'),
    sa.Column('dong_code', sa.String(length=10), nullable=False, comment='행정동 코드'),
    sa.Column('industry_code', sa.String(length=20), nullable=False, comment='업종 코드'),
    sa.Column('dong_name', sa.String(length=20), nullable=True, comment='행정동명'),
    sa.Column('industry_name', sa.String(length=50), nullable=True, comment='업종명'),
    sa.Column('store_count', sa.Integer(), nullable=True, comment='점포 수'),
    sa.Column('open_count', sa.Integer(), nullable=True, comment='개업 점포 수'),
    sa.Column('close_count', sa.Integer(), nullable=True, comment='폐업 점포 수'),
    sa.Column('closure_rate', sa.Float(), nullable=True, comment='폐업률'),
    sa.Column('franchise_count', sa.Integer(), nullable=True, comment='프랜차이즈 점포 수'),
    sa.PrimaryKeyConstraint('quarter', 'dong_code', 'industry_code')
    )
    op.create_index(op.f('ix_store_quarterly_dong_code'), 'store_quarterly', ['dong_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_quarterly_dong_code'), table_name='store_quarterly')
    op.drop_table('store_quarterly')
    op.drop_index(op.f('ix_store_info_industry_m_code'), table_name='store_info')
    op.drop_index(op.f('ix_store_info_industry_m'), table_name='store_info')
    op.drop_index(op.f('ix_store_info_dong_name'), table_name='store_info')
    op.drop_index(op.f('ix_store_info_dong_code'), table_name='store_info')
    op.drop_table('store_info')
    op.drop_table('simulation_result')
    op.drop_table('sgis_population')
    op.drop_table('sgis_household')
    op.drop_table('sgis_business')
    op.drop_index(op.f('ix_rent_cost_data_type'), table_name='rent_cost')
    op.drop_table('rent_cost')
    op.drop_table('living_population')
    op.drop_index(op.f('ix_golmok_commercial_quarter'), table_name='golmok_commercial')
    op.drop_index(op.f('ix_golmok_commercial_data_type'), table_name='golmok_commercial')
    op.drop_table('golmok_commercial')
    op.drop_table('dong_mapping')
    op.drop_index(op.f('ix_district_sales_dong_code'), table_name='district_sales')
    op.drop_table('district_sales')
    # ### end Alembic commands ###
