import subprocess
import os
import sys
from pathlib import Path

def run_script(script_path, description):
    print(f"\n{'='*60}")
    print(f"STEP: {description}")
    print(f"Script: {script_path}")
    print(f"{'='*60}\n")
    
    if not os.path.exists(script_path):
        print(f"Error: Script not found: {script_path}")
        return False

    try:
        # Run the script and capture output
        # Using sys.executable to ensure the same python interpreter is used
        result = subprocess.run([sys.executable, script_path], check=True)
        if result.returncode == 0:
            print(f"\n[SUCCESS] {description} completed.")
            return True
        else:
            print(f"\n[FAILURE] {description} failed with code {result.returncode}.")
            return False
    except subprocess.CalledProcessError as e:
        print(f"\n[FAILURE] {description} failed: {e}")
        return False
    except Exception as e:
        print(f"\n[ERROR] An error occurred: {e}")
        return False

def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-audio", help="Path to input audio file for Step 1")
    args_cli = parser.parse_args()

    base_dir = Path(__file__).resolve().parent
    
    # Define steps
    steps = [
        {
            "script": "poc/scripts/stt_to_json.py",
            "desc": "1. STT (Speech to Text) - Audio to JSON",
            "args": [] # Will be populated if input audio is provided
        },
        {
            "script": "poc/intent/poc_flash_test.py",
            "desc": "2. Intent Classification (Filter Invalid Queries)"
        },
        {
            "script": "poc/kms/simple_keyword_extractor_gemini.py",
            "desc": "3. Keyword Extraction - Extract Intent from Utterance"
        },
        {
            "script": "poc/kms/expand_keywords_comparison_gemini.py",
            "desc": "4. Keyword Expansion - Generate Search Keywords & TSV for Benchmark"
        },
        # Step 5: Run Benchmark (LYG) - Needs arguments
        {
            "script": "poc/lyg/scripts/run_benchmark.py",
            "desc": "5. Retrieval Benchmark (Vector/BM25)",
            "args": [
                "--vendors", "poc/lyg/templates/vendors.example.yaml", # Assuming template exists
                "--pipelines", "poc/lyg/templates/pipelines.example.yaml",
                "--vendor-set", "local_mock", # Changed from 'dev' to 'local_mock' for initial test
                "--pipeline", "hybrid_fuse", # Guessing pipeline name from example existence
                "--catalog", "poc/lyg/data/catalog.30cat.v3.tsv", # Use v3 if available
                "--testcases", "poc/data/expansion_result.tsv", # Generated by Step 3
                "--out", "poc/data/benchmark_out"
            ],
            "capture_output": True # Need to capture output to get run dir if needed, mainly for log
        }
    ]
    
    # Step 5: Rerank (KDG) - Needs to know the output dir of Step 4
    # Since run_benchmark allows specifying --out, we know it is poc/data/benchmark_out/<timestamp>
    # We need to find the latest timestamp dir programmatically.

    print("Starting Daiso Category Search Pipeline...")
    
    for step in steps:
        script_full_path = str(base_dir / step["script"])
        args = step.get("args", [])
        
        # Inject Input Audio for Step 1
        if "stt_to_json.py" in step["script"] and args_cli.input_audio:
            args = ["--input", args_cli.input_audio, "--output", "poc/data/stt_output.json"]
        
        # Special check for Step 4 config existence
        if "run_benchmark.py" in step["script"]:
             if not os.path.exists(str(base_dir / args[1])): # vendors
                 print(f"Warning: Vendors config not found at {args[1]}. Using template if exists or skipping.")
             # For robustness, we try to run it. If it fails, we assume user needs to config.

        cmd = [sys.executable, script_full_path] + args
        
        print(f"\n{'='*60}")
        print(f"STEP: {step['desc']}")
        print(f"Command: {' '.join(cmd)}")
        print(f"{'='*60}\n")
        
        try:
            subprocess.run(cmd, check=True)
            print(f"\n[SUCCESS] {step['desc']} completed.")
        except subprocess.CalledProcessError as e:
            print(f"\n[FAILURE] {step['desc']} failed: {e}")
            sys.exit(1)

    # Step 6: Find latest benchmark run and Rerank
    print(f"\n{'='*60}")
    print("STEP: 6. Reranking (LLM Selection)")
    print(f"{'='*60}\n")
    
    bench_out_base = base_dir / "poc/data/benchmark_out"
    if not bench_out_base.exists():
        print("Error: Benchmark output directory not found.")
        sys.exit(1)
        
    # Get latest run directory
    subdirs = [d for d in bench_out_base.iterdir() if d.is_dir()]
    if not subdirs:
        print("Error: No benchmark run directories found.")
        sys.exit(1)
        
    latest_run_dir = max(subdirs, key=lambda d: d.stat().st_mtime)
    print(f"Latest Benchmark Run: {latest_run_dir.name}")
    
    rerank_script = str(base_dir / "poc/scripts/rerank_benchmark_results.py")
    catalog_path = str(base_dir / "poc/lyg/data/catalog.30cat.tsv") # Fallback to standard name
    if (base_dir / "poc/lyg/data/catalog.30cat.v3.tsv").exists():
        catalog_path = str(base_dir / "poc/lyg/data/catalog.30cat.v3.tsv")

    rerank_out_file = str(base_dir / "poc/data/final_reranked_results.json")
    
    rerank_cmd = [
        sys.executable, rerank_script,
        "--run-dir", str(latest_run_dir),
        "--catalog", catalog_path,
        "--out", rerank_out_file
    ]
    
    try:
        subprocess.run(rerank_cmd, check=True)
        print("\n[SUCCESS] Reranking completed.")
    except subprocess.CalledProcessError:
        print("\n[FAILURE] Reranking failed.")
        sys.exit(1)

    print(f"\n{'='*60}")
    print("PIPELINE COMPLETED SUCCESSFULLY!")
    print(f"{'='*60}")
    print("Output Files:")
    print(f"1. STT Output:       poc/data/stt_output.json")
    print(f"2. Intent Analysis:  poc/data/intent_output.json")
    print(f"3. Extracted Keys:   poc/data/extracted_keywords.json")
    print(f"4. Expanded Keys:    poc/data/expansion_result.tsv")
    print(f"5. Retrieval Result: {latest_run_dir}/detail.jsonl")
    print(f"6. Final Selection:  poc/data/final_reranked_results.json")

if __name__ == "__main__":
    main()
