import React from 'react';
import ReactMarkdown from 'react-markdown';
import { motion } from 'framer-motion';
import { FileText, Download } from 'lucide-react';

interface ReportViewerProps {
  report: string;
}

const ReportViewer: React.FC<ReportViewerProps> = ({ report }) => {
  return (
    <motion.div
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      className="flex flex-col h-full bg-card rounded-2xl border border-border shadow-sm overflow-hidden"
    >
      {/* 리포트 헤더 */}
      <div className="flex items-center justify-between px-6 py-4 border-b border-border bg-muted/30">
        <div className="flex items-center gap-2">
          <FileText size={20} className="text-muted-foreground" />
          <h2 className="font-bold text-foreground">심층 분석 리포트</h2>
        </div>
        <button
          onClick={() => window.print()}
          className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-muted-foreground hover:bg-card hover:shadow-sm rounded-lg transition-all"
        >
          <Download size={14} />
          PDF 저장
        </button>
      </div>

      {/* 리포트 본문 (Markdown) */}
      <div className="flex-1 overflow-y-auto p-8 custom-scrollbar">
        <div className="max-w-none prose prose-blue prose-headings:font-black prose-p:text-muted-foreground prose-li:text-muted-foreground">
          <ReactMarkdown
            components={{
              h1: ({ node: _node, ...props }) => (
                <h1
                  className="text-3xl font-black text-foreground mb-6 border-b-2 border-border pb-2"
                  {...props}
                />
              ),
              h2: ({ node: _node, ...props }) => (
                <h2
                  className="text-xl font-bold text-foreground mt-8 mb-4 flex items-center gap-2 before:content-[''] before:w-1 before:h-6 before:bg-primary before:rounded-full"
                  {...props}
                />
              ),
              h3: ({ node: _node, ...props }) => (
                <h3 className="text-lg font-semibold text-foreground mt-6 mb-2" {...props} />
              ),
              p: ({ node: _node, ...props }) => (
                <p className="leading-relaxed mb-4 text-muted-foreground" {...props} />
              ),
              li: ({ node: _node, ...props }) => (
                <li className="mb-1 text-muted-foreground list-disc ml-4" {...props} />
              ),
              strong: ({ node: _node, ...props }) => (
                <strong className="font-bold text-foreground" {...props} />
              ),
              blockquote: ({ node: _node, ...props }) => (
                <blockquote
                  className="border-l-4 border-primary/40 bg-primary/10 p-4 my-6 italic text-foreground rounded-r-lg"
                  {...props}
                />
              ),
            }}
          >
            {report}
          </ReactMarkdown>
        </div>
      </div>

      {/* 푸터 (전문성 강조) */}
      <div className="px-8 py-4 bg-muted/50 text-[0.625rem] text-muted-foreground border-t border-border uppercase tracking-widest">
        Generated by Himidea AI Multi-Agent Engine • Seogyo-dong Context v1.0
      </div>
    </motion.div>
  );
};

export default ReportViewer;
