spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 5MB       # 파일 하나의 최대 크기
      max-request-size: 5MB   # 요청 전체의 최대 크기 (파일 여러 개 포함 가능)

#  datasource:
#    url: jdbc:postgresql://againhello.site:5432/againhello
#    username: ${POSTGRESQL_USERNAME}
#    password: ${POSTGRESQL_PASSWORD}
#    driver-class-name: org.postgresql.Driver

app:
  props:
    social:
      kakao:
        client-id: ${KAKAO_CLIENT_ID}
#        client-id: ece32edbba77663269c9d158d5b5c19e
        client-secret: ${KAKAO_CLIENT_SECRET}
#        client-secret: X2hfJvo90ByffwKDhbpdwl8m2E9zGk2M
        redirect-uri: ${KAKAO_REDIRECT_URI}
#        redirect-uri: http://localhost:3000/login
        authorization-uri: https://kauth.kakao.com/oauth/authorize
        token-uri: https://kauth.kakao.com/oauth/token
        user-info-uri: https://kapi.kakao.com/v2/user/me
        user-info-name-attribute-key: id
        client-name: Kakao

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.aix.againhello.**
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: ${JWT_SECRET}
  access-token-validity-in-seconds: 20
  refresh-token-validity-in-seconds: 604800

aws:
  region: ap-northeast-2
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
  s3:
    bucket-name: ai-himedia

clova:
  speech:
    secret: ${CLOVA_SPEECH_SECRET}
    invoke-url: ${CLOVA_SPEECH_INVOKE_URL}

