spring:
  datasource:
    url: jdbc:postgresql://15.165.139.92:5432/againhello
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  frontend: https://againhello.site
  backend: https://againhello.site


file:
  sms:
    call: /app/output/call/audio
  output:
    dir: /app/output
  upload:
    dir: /app/upload
    max-count: 3
    max-count-text: 10
    allowed-audio-extensions: mp3,aac,ac3,ogg,flac,wav,m4a
    allowed-video-extensions: avi,mp4,mov,wmv,flv,mkv
    allowed-text-extensions: txt,csv
    allowed-image-extensions: jpg,jpeg,png,webp
    max-audio-size: 5242880
    max-video-size: 314572800
    max-text-size: 314572800

app:
  props:
    social:
      kakao:
        client-id: ${KAKAO_CLIENT_ID}
        client-secret: ${KAKAO_CLIENT_SECRET}
        redirect-uri: https://againhello.site/be/member/kakao/callback
        token-uri: https://kauth.kakao.com/oauth/token
        user-info-uri: https://kapi.kakao.com/v2/user/me
        user-info-name-attribute-key: id
        client-name: Kakao