# 자동차 DTC 전문 용어 사전 (Automotive DTC Terminology Dictionary)
# 번역 시 LLM 프롬프트에 함께 제공하여 정확한 번역을 유도합니다.
# 형식: "영문": "한글"

AUTOMOTIVE_TERMS = {
    # === 핵심 단어 (Core Terms) ===
    "Circuit": "회로",
    "Sensor": "센서",
    "Control": "제어",
    "Module": "모듈",
    "Valve": "밸브",
    "Solenoid": "솔레노이드",
    "Actuator": "액추에이터",
    "Relay": "릴레이",
    "Switch": "스위치",
    "Pump": "펌프",
    "Motor": "모터",
    "Generator": "발전기",
    "Coil": "코일",
    "Heater": "히터",
    "Cooler": "쿨러",
    "Charger": "충전기",
    "Converter": "컨버터",
    "Injector": "인젝터",
    "Driver": "드라이버",
    "System": "시스템",
    "Unit": "유닛",
    "Assembly": "어셈블리",
    
    # === 상태/오류 (Status/Errors) ===
    "High Input": "입력값 높음",
    "Low Input": "입력값 낮음",
    "High": "높음",
    "Low": "낮음",
    "Open": "단선(Open)",
    "Short": "단락(Short)",
    "Shorted": "단락됨",
    "Ground": "접지",
    "Battery": "배터리",
    "Voltage": "전압",
    "Current": "전류",
    "Signal": "신호",
    "Input": "입력",
    "Output": "출력",
    "Range/Performance": "범위/성능 이상",
    "Range": "범위",
    "Performance": "성능",
    "Malfunction": "오작동",
    "Failure": "고장",
    "Fault": "결함",
    "Error": "오류",
    "Invalid": "유효하지 않음",
    "Missing": "누락됨",
    "Lost": "손실됨",
    "Intermittent": "간헐적",
    "Erratic": "불규칙한",
    "Stuck": "고착됨",
    "Stuck Open": "열린 채 고착",
    "Stuck Closed": "닫힌 채 고착",
    "Too": "과도하게",
    "Over": "초과",
    "Limit": "한계",
    "Loss": "상실",
    "Leak": "누출",
    "Detected": "감지됨",
    "Received": "수신됨",
    "Communication": "통신",
    "Implausible": "타당하지 않음(비정상)",
    "Plausibility": "타당성",
    "Threshold": "임계값",
    "Exceeded": "초과함",
    "Below": "미만",
    "Above": "이상",
    "Bank": "뱅크",
    
    # === 엔진 관련 (Engine) ===
    "Engine": "엔진",
    "Cylinder": "실린더",
    "Misfire": "실화(불발)",
    "Ignition": "점화",
    "Combustion": "연소",
    "Camshaft": "캠샤프트",
    "Crankshaft": "크랭크샤프트",
    "Timing": "타이밍",
    "Phase": "위상",
    "Idle": "공회전",
    "RPM": "RPM",
    "Knock": "노킹",
    "Detonation": "조기점화",
    "Compression": "압축",
    "Spark": "스파크",
    "Plug": "플러그",
    "Glow Plug": "글로우 플러그",
    "Coil Pack": "코일 팩",
    "Check Engine": "엔진 점검등",
    
    # === 연료 시스템 (Fuel System) ===
    "Fuel": "연료",
    "Fuel Pump": "연료 펌프",
    "Fuel Injector": "연료 인젝터",
    "Fuel Tank": "연료 탱크",
    "Fuel Pressure": "연료 압력",
    "Fuel Rail": "연료 레일",
    "Fuel Trim": "연료 보정(Trim)",
    "Lean": "희박",
    "Rich": "농후",
    "Mixture": "혼합기",
    "Air Fuel Ratio": "공연비",
    "Lambda": "람다",
    "Delivery": "공급",
    "Metering": "계량",
    
    # === 공기 흡입 시스템 (Air Intake) ===
    "Air": "공기",
    "Intake": "흡기",
    "Intake Manifold": "흡기 매니폴드",
    "MAF": "공기 유량(MAF) 센서",
    "Mass Air Flow": "공기 유량",
    "MAP": "흡기압(MAP) 센서",
    "Manifold Absolute Pressure": "매니폴드 절대 압력",
    "BARO": "대기압 센서",
    "Barometric": "대기압",
    "Throttle": "스로틀",
    "Throttle Body": "스로틀 바디",
    "Throttle Position": "스로틀 위치",
    "Air Filter": "에어 필터",
    "IAT": "흡기 온도(IAT) 센서",
    "Intake Air Temperature": "흡기 온도",
    "Flow": "흐름/유량",
    "Leakage": "누설",
    
    # === 배기 시스템 (Exhaust System) ===
    "Exhaust": "배기",
    "Exhaust Gas": "배기가스",
    "Catalyst": "촉매",
    "Catalytic Converter": "촉매 컨버터",
    "Efficiency": "효율",
    "O2": "산소",
    "O2 Sensor": "산소 센서",
    "HO2S": "가열식 산소 센서",
    "Oxygen Sensor": "산소 센서",
    "NOx": "질소산화물",
    "EGR": "배기가스 재순환(EGR)",
    "Exhaust Gas Recirculation": "배기가스 재순환(EGR)",
    "DPF": "디젤 미립자 필터(DPF)",
    "SCR": "선택적 촉매 환원(SCR)",
    "Reductant": "환원제",
    "Turbocharger": "터보차저",
    "Supercharger": "슈퍼차저",
    "Boost": "부스트",
    "Wastegate": "웨이스트게이트",
    "Bypass": "바이패스",
    "Particulate Filter": "미립자 필터",
    "Regeneration": "재생",
    
    # === 냉각 시스템 (Cooling System) ===
    "Coolant": "냉각수",
    "Coolant Temperature": "냉각수 온도",
    "Engine Coolant": "엔진 냉각수",
    "Thermostat": "서모스탯",
    "Radiator": "라디에이터",
    "Fan": "팬",
    "Cooling Fan": "냉각 팬",
    "Water Pump": "워터 펌프",
    "Temperature": "온도",
    "Overheat": "과열",
    
    # === 변속기/구동계 (Transmission/Drivetrain) ===
    "Transmission": "변속기",
    "Automatic Transmission": "자동 변속기",
    "Manual Transmission": "수동 변속기",
    "Gear": "기어",
    "Shift": "변속",
    "Shift Solenoid": "시프트 솔레노이드",
    "Clutch": "클러치",
    "Torque": "토크",
    "Torque Converter": "토크 컨버터",
    "Drive": "구동",
    "Drivetrain": "구동계",
    "Powertrain": "파워트레인",
    "Transfer Case": "트랜스퍼 케이스",
    "Differential": "디퍼렌셜",
    "Axle": "액슬",
    "Speed": "속도",
    "Vehicle Speed": "차량 속도",
    "Ratio": "비율",
    "Incorrect Gear Ratio": "기어비 부정확",
    "Contact": "접촉",
    "Connection": "연결",
    "Connector": "커넥터",
    "Harness": "와이어링/배선",
    "Circuit/Open": "회로/단선",
    "Plate": "플레이트",
    
    # === 브레이크 시스템 (Brake System) ===
    "Brake": "브레이크",
    "ABS": "ABS",
    "Anti-lock Braking": "잠김 방지 제동(ABS)",
    "Brake Pedal": "브레이크 페달",
    "Brake Fluid": "브레이크 오일",
    "Wheel Speed": "휠 속도",
    "Wheel Speed Sensor": "휠 속도 센서",
    "Parking Brake": "주차 브레이크",
    "Instrument Panel": "계기판",
    "Cluster": "계기판(클러스터)",
    "ESC": "전자식 안정 제어",
    "Traction Control": "트랙션 컨트롤",
    "Vacuum": "진공",
    
    # === 전기/전자 시스템 (Electrical) ===
    "ECM": "엔진 제어 모듈(ECM)",
    "PCM": "파워트레인 제어 모듈(PCM)",
    "TCM": "변속기 제어 모듈(TCM)",
    "BCM": "바디 제어 모듈(BCM)",
    "ECU": "전자 제어 유닛(ECU)",
    "Power": "전원",
    "Power Supply": "전원 공급",
    "Electrical": "전기",
    "Alternator": "알터네이터(발전기)",
    "Starter": "스타터",
    "Ignition Switch": "점화 스위치",
    "CAN": "CAN 통신",
    "Bus": "버스",
    "Data": "데이터",
    "Serial": "시리얼",
    "Network": "네트워크",
    
    # === 센서 종류 (Sensor Types) ===
    "Position Sensor": "위치 센서",
    "Pressure Sensor": "압력 센서",
    "Temperature Sensor": "온도 센서",
    "Speed Sensor": "속도 센서",
    "Level Sensor": "레벨 센서",
    "Oxygen Sensor": "산소 센서",
    "Knock Sensor": "노크 센서",
    "Crankshaft Position": "크랭크샤프트 위치",
    "Camshaft Position": "캠샤프트 위치",
    "Accelerator Pedal Position": "가속 페달 위치",
    "Pedal Position": "페달 위치",
    "Accelerator": "가속 페달",
    "Pedal": "페달",
    "Angle": "각도",
    "Steering Angle": "조향각",
    "Yaw Rate": "요 레이트",
    
    # === 하이브리드/전기차 (EV/Hybrid) ===
    "Hybrid": "하이브리드",
    "EV": "전기차",
    "EV Battery": "EV 배터리",
    "Battery Pack": "배터리 팩",
    "Inverter": "인버터",
    "DC": "직류(DC)",
    "AC": "교류(AC)",
    "Charging": "충전",
    "Regenerative": "회생",
    "Electric Motor": "전기 모터",
    "Drive Motor": "구동 모터",
    "High Voltage": "고전압",
    "Low Voltage": "저전압",
    "Isolation": "절연",
    
    # === 증발 시스템 (EVAP) ===
    "EVAP": "증발 가스",
    "Evaporative": "증발",
    "Evaporative Emission": "증발 가스 배출",
    "Purge": "퍼지",
    "Canister": "캐니스터",
    "Vent": "벤트",
    "Vapor": "증기",
    "Cap": "캡",
    
    # === 위치/방향 (Position/Direction) ===
    "Bank 1": "뱅크 1",
    "Bank 2": "뱅크 2",
    "Sensor 1": "센서 1",
    "Sensor 2": "센서 2",
    "Sensor 3": "센서 3",
    "Front": "전방",
    "Rear": "후방",
    "Left": "좌측",
    "Right": "우측",
    "Side": "측면",
    "Primary": "1차",
    "Secondary": "2차",
    "Upstream": "상류(Upstream)",
    "Downstream": "하류(Downstream)",
    
    # === 기타 자주 사용 (Miscellaneous) ===
    "Oil": "오일",
    "Engine Oil": "엔진 오일",
    "Transmission Fluid": "변속기 오일",
    "Fluid": "오일/유체",
    "Level": "레벨",
    "Pressure": "압력",
    "Active": "활성",
    "Passive": "수동",
    "Enable": "활성화",
    "Disable": "비활성화",
    "Test": "테스트",
    "Monitor": "모니터링",
    "Request": "요청",
    "Start": "시작",
    "Stop": "정지",
    "Cold Start": "냉간 시동",
    "Warm Up": "워밍업",
    "Cruise Control": "크루즈 컨트롤",
    "Air Suspension": "에어 서스펜션",
    "Park": "파킹",
    "Neutral": "중립",
    "VVT": "가변 밸브 타이밍(VVT)",
    "VTEC": "VTEC",
    "VCT": "가변 캠 타이밍",
    "Immobilizer": "이모빌라이저",
    "Airbag": "에어백",
    
    # === 구문 (Phrases) ===
    "Control Circuit": "제어 회로",
    "Sensor Circuit": "센서 회로",
    "Circuit Low": "회로 전압 낮음",
    "Circuit High": "회로 전압 높음",
    "Circuit Open": "회로 단선",
    "Circuit Short": "회로 단락",
    "Short To Ground": "접지 단락",
    "Short To Battery": "배터리 단락",
    "Range Performance": "범위/성능 이상",
    "Lost Communication": "통신 끊김",
    "Communication With": "통신",
    "Message From": "수신 메시지:",
    "Invalid Data": "유효하지 않은 데이터",
    "Data Received": "데이터 수신됨",
    "Too High": "부적절하게 높음",
    "Too Low": "부적절하게 낮음",
    "Stuck Off": "꺼짐 상태로 고착",
    "Stuck On": "켜짐 상태로 고착",
    "Out of Range": "범위 벗어남",
    "Below Threshold": "임계값 미만",
    "Above Threshold": "임계값 초과",
    
    # === 추가 구문 (Additional Phrases) ===
    "Lower Than Expected": "예상보다 낮음",
    "Higher Than Expected": "예상보다 높음",
    "Than Expected": "예상치 비교",
    "Detection": "감지",
    "Random": "무작위",
    "Slow Response": "느린 응답",
    "Fast Response": "빠른 응답",
    "Label": "라벨",
    "Reset": "리셋/초기화",
    "Insufficient": "불충분",
    "Improper": "부적절한",
    "Correlation": "상관관계(동기화) 이상",
    "Expected": "예상됨",
    "Closed": "닫힘",
    "Electrical Load Detector": "전기 부하 감지기",
    "ELD": "전기 부하 감지기",
    "CKP": "크랭크샤프트 위치(CKP)",
    "CMP": "캠샤프트 위치(CMP)",
    "Source": "공급원",
    "Load": "부하",
    "Detector": "감지기",
}


# 번역 프롬프트용 문자열 생성
def get_terms_for_prompt():
    """LLM 프롬프트에 포함할 용어 사전 문자열 생성"""
    lines = ["[Automotive Term Dictionary - Use these translations:]"]
    for en, ko in AUTOMOTIVE_TERMS.items():
        lines.append(f"- {en} = {ko}")
    return "\n".join(lines)

if __name__ == "__main__":
    print(f"Total terms: {len(AUTOMOTIVE_TERMS)}")
    print("\n--- Sample for Prompt ---")
    print(get_terms_for_prompt()[:2000] + "...")
