from typing import Dict, List, Any

# 탈모 단계별 제품 데이터 구조 (0-3단계로 변경)
HAIR_LOSS_STAGE_PRODUCTS: Dict[int, List[dict]] = {
    0: [  # 0단계: 예방용 샴푸, 두피 클렌저, 생활습관 가이드
        {
            "productId": "stage0-1",
            "productName": "예방용 두피 건강 샴푸",
            "productPrice": 15000,
            "productRating": 4.6,
            "productReviewCount": 324,
            "productImage": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage0-1",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "예방케어",
            "category1": "헤어케어",
            "category2": "예방샴푸",
            "category3": "두피건강",
            "category4": "0단계",
            "description": "탈모 예방을 위한 두피 건강 샴푸",
            "ingredients": ["케라틴", "비오틴", "판테놀", "아르간오일"],
            "suitableStages": [0, 1],
        },
        {
            "productId": "stage0-2",
            "productName": "두피 클렌저",
            "productPrice": 18000,
            "productRating": 4.4,
            "productReviewCount": 267,
            "productImage": "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage0-2",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "예방케어",
            "category1": "헤어케어",
            "category2": "두피클렌저",
            "category3": "예방용",
            "category4": "0단계",
            "description": "두피 노폐물 제거 및 순환 개선 클렌저",
            "ingredients": ["살리실릭애씨드", "티트리오일", "멘톨"],
            "suitableStages": [0, 1],
        },
        {
            "productId": "stage0-3",
            "productName": "생활습관 가이드 패키지",
            "productPrice": 25000,
            "productRating": 4.8,
            "productReviewCount": 189,
            "productImage": "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage0-3",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "예방케어",
            "category1": "헤어케어",
            "category2": "생활습관가이드",
            "category3": "예방용",
            "category4": "0단계",
            "description": "탈모 예방을 위한 생활습관 가이드 및 영양제",
            "ingredients": ["비오틴", "아연", "셀레늄", "비타민D"],
            "suitableStages": [0, 1, 2],
        },
        {
            "productId": "stage0-4",
            "productName": "두피 영양 에센스",
            "productPrice": 32000,
            "productRating": 4.5,
            "productReviewCount": 215,
            "productImage": "https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage0-4",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "예방케어",
            "category1": "헤어케어",
            "category2": "두피에센스",
            "category3": "예방용",
            "category4": "0단계",
            "description": "두피에 영양을 공급하는 예방 에센스",
            "ingredients": ["나이아신아마이드", "판테놀", "비타민B5", "카페인"],
            "suitableStages": [0, 1],
        },
    ],
    1: [  # 1단계: 탈모 방지 샴푸, 영양제, 두피 토닉
        {
            "productId": "stage1-1",
            "productName": "탈모 방지 샴푸",
            "productPrice": 22000,
            "productRating": 4.5,
            "productReviewCount": 234,
            "productImage": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage1-1",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "탈모방지",
            "category1": "헤어케어",
            "category2": "탈모샴푸",
            "category3": "방지용",
            "category4": "1단계",
            "description": "초기 탈모 방지를 위한 전문 샴푸",
            "ingredients": ["케라틴", "비오틴", "판테놀", "아르간오일"],
            "suitableStages": [1, 2],
        },
        {
            "productId": "stage1-2",
            "productName": "모발 강화 영양제",
            "productPrice": 35000,
            "productRating": 4.7,
            "productReviewCount": 189,
            "productImage": "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage1-2",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "탈모방지",
            "category1": "헤어케어",
            "category2": "영양제",
            "category3": "모발강화",
            "category4": "1단계",
            "description": "모발 건강을 위한 종합 영양제",
            "ingredients": ["비오틴", "아연", "셀레늄", "비타민E"],
            "suitableStages": [1, 2, 3],
        },
        {
            "productId": "stage1-3",
            "productName": "두피 토닉",
            "productPrice": 28000,
            "productRating": 4.3,
            "productReviewCount": 156,
            "productImage": "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage1-3",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "탈모방지",
            "category1": "헤어케어",
            "category2": "두피토닉",
            "category3": "방지용",
            "category4": "1단계",
            "description": "두피 순환 개선 및 모발 성장 촉진 토닉",
            "ingredients": ["민들레추출물", "로즈마리", "멘톨", "카페인"],
            "suitableStages": [1, 2],
        },
        {
            "productId": "stage1-4",
            "productName": "모발 강화 세럼",
            "productPrice": 38000,
            "productRating": 4.6,
            "productReviewCount": 203,
            "productImage": "https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage1-4",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "탈모방지",
            "category1": "헤어케어",
            "category2": "모발세럼",
            "category3": "방지용",
            "category4": "1단계",
            "description": "모근 강화 및 모발 탄력 증진 세럼",
            "ingredients": ["펩타이드", "히알루론산", "콜라겐", "비타민E"],
            "suitableStages": [1, 2],
        },
    ],
    2: [  # 2단계: 두피 앰플, 기능성 치료제, 홈케어 기기
        {
            "productId": "stage2-1",
            "productName": "두피 앰플",
            "productPrice": 45000,
            "productRating": 4.6,
            "productReviewCount": 267,
            "productImage": "https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage2-1",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "기능성치료",
            "category1": "헤어케어",
            "category2": "두피앰플",
            "category3": "기능성",
            "category4": "2단계",
            "description": "두피 모낭 활성화를 위한 고농축 앰플",
            "ingredients": ["펩타이드", "케라틴", "비타민E", "아르간오일"],
            "suitableStages": [2, 3],
        },
        {
            "productId": "stage2-2",
            "productName": "기능성 치료제",
            "productPrice": 55000,
            "productRating": 4.4,
            "productReviewCount": 198,
            "productImage": "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage2-2",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "기능성치료",
            "category1": "헤어케어",
            "category2": "치료제",
            "category3": "기능성",
            "category4": "2단계",
            "description": "모발 성장 촉진을 위한 기능성 치료제",
            "ingredients": ["미녹시딜", "케라틴", "아미노산", "펩타이드"],
            "suitableStages": [2, 3],
        },
        {
            "productId": "stage2-3",
            "productName": "홈케어 기기",
            "productPrice": 120000,
            "productRating": 4.7,
            "productReviewCount": 145,
            "productImage": "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage2-3",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "기능성치료",
            "category1": "헤어케어",
            "category2": "홈케어기기",
            "category3": "기능성",
            "category4": "2단계",
            "description": "두피 마사지 및 모발 성장 촉진 홈케어 기기",
            "ingredients": ["LED광선", "진동마사지", "열치료"],
            "suitableStages": [2, 3],
        },
        {
            "productId": "stage2-4",
            "productName": "두피 스케일링 솔루션",
            "productPrice": 42000,
            "productRating": 4.5,
            "productReviewCount": 178,
            "productImage": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage2-4",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "기능성치료",
            "category1": "헤어케어",
            "category2": "두피스케일링",
            "category3": "기능성",
            "category4": "2단계",
            "description": "모공 청결 및 두피 환경 개선 스케일링 솔루션",
            "ingredients": ["살리실릭애씨드", "AHA", "BHA", "티트리"],
            "suitableStages": [2, 3],
        },
    ],
    3: [  # 3단계: 전문 클리닉 연계, 고농축 앰플, 가발·헤어시스템
        {
            "productId": "stage3-1",
            "productName": "전문 클리닉 연계 서비스",
            "productPrice": 150000,
            "productRating": 4.8,
            "productReviewCount": 312,
            "productImage": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage3-1",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "전문치료",
            "category1": "헤어케어",
            "category2": "전문클리닉",
            "category3": "연계서비스",
            "category4": "3단계",
            "description": "전문 탈모 클리닉과 연계된 맞춤형 치료 서비스",
            "ingredients": ["전문의상담", "맞춤치료", "지속관리"],
            "suitableStages": [3],
        },
        {
            "productId": "stage3-2",
            "productName": "고농축 앰플",
            "productPrice": 85000,
            "productRating": 4.9,
            "productReviewCount": 278,
            "productImage": "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage3-2",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "전문치료",
            "category1": "헤어케어",
            "category2": "고농축앰플",
            "category3": "전문용",
            "category4": "3단계",
            "description": "고농축 성분으로 모발 성장을 촉진하는 전문 앰플",
            "ingredients": ["미녹시딜 10%", "케라틴", "아미노산", "펩타이드"],
            "suitableStages": [3],
        },
        {
            "productId": "stage3-3",
            "productName": "가발·헤어시스템",
            "productPrice": 200000,
            "productRating": 4.7,
            "productReviewCount": 189,
            "productImage": "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage3-3",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "전문치료",
            "category1": "헤어케어",
            "category2": "가발헤어시스템",
            "category3": "전문용",
            "category4": "3단계",
            "description": "자연스러운 모발 복원을 위한 가발 및 헤어시스템",
            "ingredients": ["천연모발", "전문가공", "맞춤제작"],
            "suitableStages": [3],
        },
        {
            "productId": "stage3-4",
            "productName": "전문 두피 관리 세트",
            "productPrice": 95000,
            "productRating": 4.8,
            "productReviewCount": 234,
            "productImage": "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=200&fit=crop&crop=center",
            "productUrl": "https://www.11st.co.kr/products/stage3-4",
            "mallName": "11번가",
            "maker": "헤어케어 전문",
            "brand": "전문치료",
            "category1": "헤어케어",
            "category2": "관리세트",
            "category3": "전문용",
            "category4": "3단계",
            "description": "전문 두피 관리를 위한 종합 케어 세트",
            "ingredients": ["고농축펩타이드", "미녹시딜", "케라틴", "비타민복합체"],
            "suitableStages": [3],
        },
    ],
}

STAGE_DESCRIPTIONS = {
    0: "예방 단계 (예방용 샴푸, 두피 클렌저, 생활습관 가이드, 두피 에센스)",
    1: "초기 탈모 (탈모 방지 샴푸, 영양제, 두피 토닉, 모발 세럼)",
    2: "진행 단계 (두피 앰플, 기능성 치료제, 홈케어 기기, 두피 스케일링)",
    3: "전문 단계 (전문 클리닉 연계, 고농축 앰플, 가발·헤어시스템, 전문 관리 세트)",
}


