"""add conversation_summary to call_logs

Revision ID: f1a2b3c4d5e6
Revises: bbc4f5258de3
Create Date: 2025-10-17 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1a2b3c4d5e6'
down_revision: Union[str, None] = 'b1c2d3e4f5g6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # call_logs 테이블에 conversation_summary 컬럼 추가
    op.add_column('call_logs', sa.Column('conversation_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # call_logs 테이블에서 conversation_summary 컬럼 제거
    op.drop_column('call_logs', 'conversation_summary')
    # ### end Alembic commands ###

