"""add is_shared_with_caregiver to todos

Revision ID: a1b2c3d4e5f7
Revises: f1a2b3c4d5e6
Create Date: 2025-10-21 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f7'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # todos 테이블에 is_shared_with_caregiver 컬럼 추가
    op.add_column('todos', 
        sa.Column('is_shared_with_caregiver', sa.Boolean(), 
                  nullable=False, server_default='true')
    )
    
    # 기존 데이터는 모두 공유로 설정 (기존 동작 유지)
    # server_default='true'로 이미 처리되었지만 명시적으로 한 번 더 업데이트
    op.execute("""
        UPDATE todos 
        SET is_shared_with_caregiver = true
        WHERE is_shared_with_caregiver IS NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # todos 테이블에서 is_shared_with_caregiver 컬럼 제거
    op.drop_column('todos', 'is_shared_with_caregiver')
    # ### end Alembic commands ###

