"""add push notification detail settings to user_settings

Revision ID: d5f8e9a1b2c3
Revises: c4ea574a82f1
Create Date: 2025-10-23 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f8e9a1b2c3'
down_revision: Union[str, None] = 'c4ea574a82f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # UserSettings 테이블에 푸시 알림 세부 설정 컬럼 추가
    op.add_column('user_settings', sa.Column('push_todo_reminder_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('user_settings', sa.Column('push_todo_incomplete_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('user_settings', sa.Column('push_todo_created_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('user_settings', sa.Column('push_diary_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('user_settings', sa.Column('push_call_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('user_settings', sa.Column('push_connection_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'push_connection_enabled')
    op.drop_column('user_settings', 'push_call_enabled')
    op.drop_column('user_settings', 'push_diary_enabled')
    op.drop_column('user_settings', 'push_todo_created_enabled')
    op.drop_column('user_settings', 'push_todo_incomplete_enabled')
    op.drop_column('user_settings', 'push_todo_reminder_enabled')
    # ### end Alembic commands ###

