"""add title and mood to diaries, add push_token to users

Revision ID: c4ea574a82f1
Revises: a1b2c3d4e5f7
Create Date: 2025-10-22 01:44:52.196570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4ea574a82f1'
down_revision: Union[str, None] = 'a1b2c3d4e5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diaries', sa.Column('title', sa.String(length=200), nullable=True))
    op.add_column('diaries', sa.Column('mood', sa.String(length=50), nullable=True))
    op.alter_column('todos', 'is_shared_with_caregiver',
               existing_type=sa.BOOLEAN(),
               comment='보호자와 공유 여부 (True: 공유, False: 어르신만)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('user_settings', 'auto_call_enabled')
    op.drop_column('user_settings', 'scheduled_call_time')
    op.add_column('users', sa.Column('push_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('push_token_updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_push_token'), 'users', ['push_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_push_token'), table_name='users')
    op.drop_column('users', 'push_token_updated_at')
    op.drop_column('users', 'push_token')
    op.add_column('user_settings', sa.Column('scheduled_call_time', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.add_column('user_settings', sa.Column('auto_call_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('todos', 'is_shared_with_caregiver',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='보호자와 공유 여부 (True: 공유, False: 어르신만)',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('diaries', 'mood')
    op.drop_column('diaries', 'title')
    # ### end Alembic commands ###

