"""add user_settings table

Revision ID: 302c7ff1293d
Revises: aec47b8e33b6
Create Date: 2025-10-15 08:27:55.955067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '302c7ff1293d'
down_revision: Union[str, None] = 'aec47b8e33b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('auto_call_enabled', sa.Boolean(), nullable=True))
    op.add_column('user_settings', sa.Column('scheduled_call_time', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'scheduled_call_time')
    op.drop_column('user_settings', 'auto_call_enabled')
    # ### end Alembic commands ###