"""Initial tables with all columns

Revision ID: aec47b8e33b6
Revises: 
Create Date: 2025-10-16 02:17:59.783128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec47b8e33b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('ELDERLY', 'CAREGIVER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('auth_provider', sa.Enum('EMAIL', 'GOOGLE', 'KAKAO', name='authprovider'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('call_logs',
    sa.Column('call_id', sa.String(length=36), nullable=False),
    sa.Column('elderly_id', sa.String(length=36), nullable=False),
    sa.Column('call_status', sa.Enum('INITIATED', 'RINGING', 'ANSWERED', 'COMPLETED', 'MISSED', 'REJECTED', 'FAILED', name='callstatus'), nullable=False),
    sa.Column('call_start_time', sa.DateTime(), nullable=True),
    sa.Column('call_end_time', sa.DateTime(), nullable=True),
    sa.Column('call_duration', sa.Integer(), nullable=True),
    sa.Column('audio_file_url', sa.String(length=500), nullable=True),
    sa.Column('twilio_call_sid', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['elderly_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('call_id'),
    sa.UniqueConstraint('twilio_call_sid')
    )
    op.create_table('call_settings',
    sa.Column('setting_id', sa.String(length=36), nullable=False),
    sa.Column('elderly_id', sa.String(length=36), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY_3', 'WEEKLY_5', 'CUSTOM', name='callfrequency'), nullable=True),
    sa.Column('call_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['elderly_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('setting_id'),
    sa.UniqueConstraint('elderly_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('DIARY_CREATED', 'TODO_REMINDER', 'CONNECTION_REQUEST', 'CONNECTION_ACCEPTED', 'EMOTION_ALERT', 'CALL_MISSED', 'COMMENT_ADDED', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_id', sa.String(length=36), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_pushed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('user_connections',
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('caregiver_id', sa.String(length=36), nullable=False),
    sa.Column('elderly_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'REJECTED', name='connectionstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['caregiver_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['elderly_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('connection_id')
    )
    op.create_table('user_settings',
    sa.Column('setting_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('auto_diary_enabled', sa.Boolean(), nullable=True),
    sa.Column('push_notification_enabled', sa.Boolean(), nullable=True),
    sa.Column('language_preference', sa.String(length=10), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('setting_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('call_transcripts',
    sa.Column('transcript_id', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=False),
    sa.Column('speaker', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['call_logs.call_id'], ),
    sa.PrimaryKeyConstraint('transcript_id')
    )
    op.create_table('diaries',
    sa.Column('diary_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_type', sa.Enum('ELDERLY', 'CAREGIVER', 'AI', name='authortype'), nullable=False),
    sa.Column('is_auto_generated', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='diarystatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['call_id'], ['call_logs.call_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('diary_id')
    )
    op.create_table('emotion_logs',
    sa.Column('emotion_id', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=False),
    sa.Column('emotion_type', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', name='emotiontype'), nullable=False),
    sa.Column('emotion_score', sa.Float(), nullable=False),
    sa.Column('detected_keywords', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['call_logs.call_id'], ),
    sa.PrimaryKeyConstraint('emotion_id')
    )
    op.create_table('todos',
    sa.Column('todo_id', sa.String(length=36), nullable=False),
    sa.Column('elderly_id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('call_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('MEDICINE', 'EXERCISE', 'MEAL', 'HOSPITAL', 'OTHER', name='todocategory'), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('due_time', sa.Time(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('recurring_type', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='recurringtype'), nullable=True),
    sa.Column('recurring_interval', sa.Integer(), nullable=True),
    sa.Column('recurring_days', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('recurring_day_of_month', sa.Integer(), nullable=True),
    sa.Column('recurring_start_date', sa.Date(), nullable=True),
    sa.Column('recurring_end_date', sa.Date(), nullable=True),
    sa.Column('parent_recurring_id', sa.String(length=36), nullable=True),
    sa.Column('creator_type', sa.Enum('CAREGIVER', 'AI', 'ELDERLY', name='creatortype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='todostatus'), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['call_logs.call_id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['elderly_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['parent_recurring_id'], ['todos.todo_id'], ),
    sa.PrimaryKeyConstraint('todo_id')
    )
    op.create_table('diary_comments',
    sa.Column('comment_id', sa.String(length=36), nullable=False),
    sa.Column('diary_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diary_id'], ['diaries.diary_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('diary_photos',
    sa.Column('photo_id', sa.String(length=36), nullable=False),
    sa.Column('diary_id', sa.String(length=36), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['diary_id'], ['diaries.diary_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('photo_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diary_photos')
    op.drop_table('diary_comments')
    op.drop_table('todos')
    op.drop_table('emotion_logs')
    op.drop_table('diaries')
    op.drop_table('call_transcripts')
    op.drop_table('user_settings')
    op.drop_table('user_connections')
    op.drop_table('notifications')
    op.drop_table('call_settings')
    op.drop_table('call_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###