"""
캘린더 관련 프롬프트들
"""

from .save_confirmation import (
    CALENDAR_SAVE_CONFIRMATION_PROMPT,
    CALENDAR_SAVE_FAILURE_PROMPT,
    CALENDAR_MEAL_PLAN_VALIDATION_PROMPT,
    RESTAURANT_CALENDAR_SAVE_PROMPT
)

__all__ = [
    "CALENDAR_SAVE_CONFIRMATION_PROMPT",
    "CALENDAR_SAVE_FAILURE_PROMPT",
    "CALENDAR_MEAL_PLAN_VALIDATION_PROMPT",
    "RESTAURANT_CALENDAR_SAVE_PROMPT"
]