# 1. Node.js를 기반으로 React 앱 빌드
FROM node:18 as build

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --production
COPY . .

# ✅ 환경 변수 수동 추가
ARG REACT_APP_NAVER_CLIENT_ID
ARG REACT_APP_NAVER_REDIRECT_URI
ARG REACT_APP_KAKAO_ID
ARG REACT_APP_KAKAO_REDIRECT_URI
ARG REACT_APP_GOOGLE_CLIENT_ID
ARG REACT_APP_GOOGLE_REDIRECT_URI

ENV REACT_APP_NAVER_CLIENT_ID=$REACT_APP_NAVER_CLIENT_ID
ENV REACT_APP_NAVER_REDIRECT_URI=$REACT_APP_NAVER_REDIRECT_URI
ENV REACT_APP_KAKAO_ID=$REACT_APP_KAKAO_ID
ENV REACT_APP_KAKAO_REDIRECT_URI=$REACT_APP_KAKAO_REDIRECT_URI
ENV REACT_APP_GOOGLE_CLIENT_ID=$REACT_APP_GOOGLE_CLIENT_ID
ENV REACT_APP_GOOGLE_REDIRECT_URI=$REACT_APP_GOOGLE_REDIRECT_URI

RUN npm run build

# 2. Nginx로 React 앱 실행
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
