# # Miniconda + Python 3.12 기반 이미지
# FROM continuumio/miniconda3:latest

# # 작업 디렉토리 설정
# WORKDIR /app

# # 필요한 환경변수 설정
# ENV PYTHONDONTWRITEBYTECODE=1
# ENV PYTHONUNBUFFERED=1

# # conda 환경 만들기 + ffmpeg 설치
# RUN conda update -n base -c defaults conda && \
#     conda create -n flowy python=3.12 -y && \
#     conda install -n flowy -c conda-forge ffmpeg tokenizers -y

# # Conda 환경 활성화 설정
# SHELL ["conda", "run", "-n", "flowy", "/bin/bash", "-c"]

# # requirements 복사
# COPY requirements.txt .

# # PyTorch 계열 패키지 (GPU 지원 버전은 별도 인덱스 필요)
# RUN pip install --no-cache-dir \
#     torch==2.7.0+cu118 \
#     torchaudio==2.7.0+cu118 \
#     torchvision==0.22.0+cu118 \
#     --extra-index-url https://download.pytorch.org/whl/cu118

# # 나머지 패키지 설치 (tokenizers, torch 등은 이미 설치되어 있음)
# RUN pip install --no-cache-dir -r requirements.txt

# # 앱 소스 복사
# COPY . .

# # FastAPI 실행
# # CMD ["conda", "run", "-n", "flowy", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

# Miniconda 기반 이미지
FROM continuumio/miniconda3:latest

# 작업 디렉토리 설정
WORKDIR /app

# 필요한 환경변수 설정
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# conda를 통해 ffmpeg 및 tokenizers 설치
RUN conda update -n base -c defaults conda && \
    conda install -c conda-forge ffmpeg tokenizers python=3.12 -y

# requirements 복사
COPY requirements.txt .

# PyTorch 계열 패키지 (GPU 지원 버전은 별도 인덱스 필요)
RUN pip install --no-cache-dir \
    torch==2.7.0+cu118 \
    torchaudio==2.7.0+cu118 \
    torchvision==0.22.0+cu118 \
    --extra-index-url https://download.pytorch.org/whl/cu118

# 나머지 패키지 설치
RUN pip install --no-cache-dir -r requirements.txt

# 앱 소스 복사
COPY . .

# FastAPI 실행 
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--log-level", "debug", "--access-log"]