spring.application.name=auth

# .env 파일 로드
spring.config.import=optional:file:.env[.properties]

# Server
server.port=8080

# Database
spring.jpa.open-in-view=false
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA 설정
# Hibernate 자동 DDL 생성 비활성화
spring.jpa.hibernate.ddl-auto=update
# MySQL8 방언 지정
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# SQL 로그 포맷팅
spring.jpa.properties.hibernate.format_sql=true
# SQL 쿼리 출력
spring.jpa.show-sql=true

# OAuth2 클라이언트 설정 (Kakao)
# 실제 값은 환경 변수로 설정 필요
spring.security.oauth2.client.registration.kakao.client-id=${KAKAO_CLIENT_ID}
spring.security.oauth2.client.registration.kakao.client-secret=${KAKAO_CLIENT_SECRET}
spring.security.oauth2.client.registration.kakao.scope=profile_nickname
spring.security.oauth2.client.registration.kakao.redirect-uri=http://127.0.0.1:3000/login/oauth2/code/kakao
spring.security.oauth2.client.registration.kakao.client-name=Kakao
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.client-authentication-method=POST

# Kakao Provider 설정 (필수)
spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id

# JWT 설정
# JWT 서명 키 (기본값)
jwt.secret=${JWT_SECRET}
# Access Token 만료시간 (밀리초) - 15분
jwt.access-token-expiration=900000
# Refresh Token 만료시간 (밀리초) - 7일
jwt.refresh-token-expiration=604800000