import type { Plan } from '../types';

export const PLANS: Plan[] = [
  {
    id: 'starter',
    name: 'Starter',
    target: '가맹 준비 ~ 초기 본부',
    price: '₩0',
    priceNote: '/ 월',
    badge: '🌱',
    cta: '무료로 시작하기',
    highlighted: false,
    features: [
      { text: '상권 분석 1일 3회 제한', included: true },
      { text: '서울 한정 데이터', included: true },
      { text: '기본 리포트', included: true },
      { text: '카니발리제이션 경고', included: false },
      { text: '상세 AI 리포트', included: false },
      { text: '데이터 CSV 내보내기', included: false },
      { text: '전국 데이터 확장', included: false },
      { text: 'API 액세스', included: false },
    ],
  },
  {
    id: 'growth',
    name: 'Growth',
    target: '가맹점 30호점 미만 (성장기)',
    price: '₩290,000',
    priceNote: '/ 월',
    badge: '🚀',
    badgeLabel: 'Most Popular',
    cta: 'Growth 시작하기',
    highlighted: true,
    features: [
      { text: '무제한 시뮬레이션', included: true },
      { text: '카니발리제이션 경고', included: true },
      { text: '상세 AI 리포트', included: true },
      { text: '이메일 알림', included: true },
      { text: '데이터 CSV 내보내기', included: true },
      { text: '전국 데이터 확장', included: false },
      { text: 'API 액세스', included: false },
      { text: '전담 매니저 배정', included: false },
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    target: '가맹점 30호점 이상 (전국 단위)',
    price: '별도 문의',
    priceNote: '',
    badge: '🏢',
    cta: '도입 문의하기',
    highlighted: false,
    features: [
      { text: 'Growth 전체 기능 포함', included: true },
      { text: '전국 데이터 확장', included: true },
      { text: '출점 성공률 AI 예측 모델링', included: true },
      { text: 'API 액세스', included: true },
      { text: '전담 매니저 배정', included: true },
      { text: 'SLA 보장', included: true },
    ],
  },
];
