"""
공통 프롬프트 패키지
여러 모듈에서 공유하는 프롬프트 템플릿을 제공합니다.
"""

from common_prompts.prompts import (
    AGENT_CONTEXT_PROMPT,
    QDRANT_INSIGHTS_PROMPT,
    QDRANT_SEARCH_PROMPT,
    CATEGORY_ROUTING_PROMPT,
    AGENT_CONTEXT_BUILDING_PROMPT
)

__all__ = [
    "AGENT_CONTEXT_PROMPT",
    "QDRANT_INSIGHTS_PROMPT",
    "QDRANT_SEARCH_PROMPT", 
    "CATEGORY_ROUTING_PROMPT",
    "AGENT_CONTEXT_BUILDING_PROMPT"
] 