"""create table

Revision ID: 8d92cc462a1a
Revises: 296ac3f1fd58
Create Date: 2025-06-19 02:36:58.048512

"""
from typing import Sequence, Union

from alembic import op
from pgvector.sqlalchemy import Vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d92cc462a1a'
down_revision: Union[str, None] = '296ac3f1fd58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    op.alter_column('draft_log', 'draft_trigger',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('draft_log', 'ref_interdoc_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.drop_constraint(op.f('meeting_project_id_fkey'), 'meeting', type_='foreignkey')
    op.create_foreign_key(None, 'meeting', 'project', ['project_id'], ['project_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_user_project_id_fkey'), 'project_user', type_='foreignkey')
    op.create_foreign_key(None, 'project_user', 'project', ['project_id'], ['project_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_user', type_='foreignkey')
    op.create_foreign_key(op.f('project_user_project_id_fkey'), 'project_user', 'project', ['project_id'], ['project_id'])
    op.drop_constraint(None, 'meeting', type_='foreignkey')
    op.create_foreign_key(op.f('meeting_project_id_fkey'), 'meeting', 'project', ['project_id'], ['project_id'])
    op.alter_column('draft_log', 'ref_interdoc_id',
               existing_type=sa.String(length=512),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('draft_log', 'draft_trigger',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_table('langchain_pg_embedding',
    sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('embedding', Vector(None), autoincrement=False, nullable=True),
    sa.Column('document', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('custom_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['langchain_pg_collection.uuid'], name=op.f('langchain_pg_embedding_collection_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('langchain_pg_embedding_pkey'))
    )
    op.create_table('langchain_pg_collection',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('langchain_pg_collection_pkey'))
    )
    op.create_table('admin',
    sa.Column('admin_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('admin_company_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('admin_sysrole_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_company_id'], ['company.company_id'], name=op.f('admin_admin_company_id_fkey')),
    sa.ForeignKeyConstraint(['admin_sysrole_id'], ['sysrole.sysrole_id'], name=op.f('admin_admin_sysrole_id_fkey')),
    sa.PrimaryKeyConstraint('admin_id', name=op.f('admin_pkey'))
    )
    # ### end Alembic commands ###
