"""create table

Revision ID: c171e2354d7d
Revises: ad3eadd63842
Create Date: 2025-06-10 09:30:10.238699

"""
from typing import Sequence, Union

from alembic import op
from pgvector.sqlalchemy import Vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c171e2354d7d'
down_revision: Union[str, None] = 'ad3eadd63842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedbacktype', 'feedback_detail')
    op.drop_column('meeting', 'meeting_audio_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('meeting_audio_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('feedbacktype', sa.Column('feedback_detail', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
