# 부산 2박 3일 데이터 

# input_data = {
#     "main_location": "부산광역시 - 부산광역시",
#     "start_date": "2025-03-05",
#     "end_date": "2025-03-07",
#     "ages": "30대",
#     "companion_count" : [{"label": "성인", "count": 2}],
#     "concepts" : ["데이트", "힐링", "낮술", "해산물"]
# }

# 각 에이전트 결과 : 식당 11개, 관광 6개, 카페 6개, 숙소 5개 반환
def create_dummy_data():
    return {
        'restaurant': {
            'message': '요청이 성공적으로 처리되었습니다.',
            'plan': {
                'name': '여행 일정',
                'start_date': '2025-03-05',
                'end_date': '2025-03-07',
                'main_location': '부산광역시 -  부산광역시',
                'ages': '30대',
                'companion_count': 2,
                'concepts': '맛집',
                'member_id': 6,
                'created_at': '2025-02-24',
                'updated_at': '2025-02-24'
                },
            'spots': [
                {
                    'kor_name': '금수복국 해운대본점',
                    'eng_name': 'Geumsu Bokkuk Haeundae',
                    'description': '50년 전통의 복국 전문점으로, 신선한 재료로 만든 복국이 일품입니다. 해운대 해수욕장 근처에 위치해 있어 관광 후 방문하기 좋으며, 아늑한 분위기에서 식사를 즐길 수 있습니다.',
                    'address': '부산 해운대구 중동1로43번길 23',
                    'url': 'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=12251fce-8e26-4121-9af1-9d8a7ebf2ab4', 
                    'image_url': 'https://ldb-phinf.pstatic.net/20151005_54/1444039596873PWKUo_JPEG/166955593649903_8.jpg',
                    'map_url': 'https://map.kakao.com/link/map/8708426',
                    'latitude': 35.1623954243218,
                    'longitude': 129.164447392476,
                    'spot_category': 2,
                    'phone_number': '051-742-3600',
                    'business_status': True,
                    'business_hours': '매일 10:00 ~ 22:00',
                    'order': 0,
                    'day_x': 0,
                    'spot_time': None
                },
                {
                    'kor_name': '평산옥',
                    'eng_name': 'Pyeongsanok',
                    'description': '부산역 근처에 위 치한 100년 전통의 돼지수육 전문점으로, 부드러운 수육과 맑은 국물이 특징입니다. 가족 단위 방문에 적합하며, 오랜 역사를 자랑하는 맛집입니다.',
                    'address': '부산 동구 초량중로 26',
                    'url': 'https://www.visitbusan.net/index.do?menuCd=DOM_000000201002001000&uc_seq=1104',
                    'image_url': 'https://d2uja84sd90jmv.cloudfront.net/posts/CxXuf6oCeRbLLdTN2vi6Nw/ms.jpg',
                    'map_url': 'https://map.kakao.com/link/map/10036299',
                    'latitude': 35.114286998827694,
                    'longitude': 129.03710061120927,
                    'spot_category': 2,
                    'phone_number': '051-468-6255',
                    'business_status': True,
                    'business_hours': '매일 10:00 ~ 22:00',
                    'order': 0,
                    'day_x': 0, 
                    'spot_time': None
                },
                {
                    'kor_name': '60년전통 할매국밥',
                    'eng_name': '60-Year Traditional Halmae Gukbap',
                    'description': '부산의 전통적인 국밥 전문점으로, 깊고 진한 국물과 신선한 재료로 만든 국밥이 인기입니다. 현지인들에게 사랑받는 맛집입니다.',
                    'address': '부산 동구 중앙대로533번길 4',
                    'url': 'https://www.example.com',
                    'image_url': 'https://pup-review-phinf.pstatic.net/MjAyMzAyMDNfMTYg/MDAxNjc1MzkxODEzMTI0.mMXfTkaKTovLoLyeQ90iiYqOodtcUsMfbHRsezQQpRcg.PKlCa6232IB8zzhGE31pKWWjBU7FnECatGPI6PtV6Jcg.JPEG/4FA785B2-6DD6-443D-BC3E-AD9B977E8AD2.jpeg?type=w828_60_sharpen',
                    'map_url': 'https://map.kakao.com/link/map/16694746',
                    'latitude': 35.1410107834473,
                    'longitude': 129.056166680599,
                    'spot_category': 2,
                    'phone_number': '051-646-6295',
                    'business_status': True,
                    'business_hours': '매일 10:00 ~ 22:00',
                    'order': 0,
                    'day_x': 0,
                    'spot_time': None
                },
                {
                    'kor_name': '할매집 돼지국밥 해운대본점',
                    'eng_name': 'Halmae House Pork Soup Haeundae Main Store',
                    'description': '해운대에 위치한 돼지국밥 전문점으로, 진한 국물과 부드러운 고기가 특징입니다. 가족 단위 방문에 적합합니다.',
                    'address': '부산 해운대구 구남로8번길 48',
                    'url': 'https://www.example.com',
                    'image_url': 'http://img.ezmember.co.kr/cache/board/2013/11/07/2c5e7c2d22c7389f5398a26c9406d28f.jpg',
                    'map_url': 'https://map.kakao.com/link/map/162829160',
                    'latitude': 35.161994102220156,
                    'longitude': 129.15683880915927,
                    'spot_category': 2,
                    'phone_number': '051-741-1152',
                    'business_status': True,
                    'business_hours': '매일 10:00 ~ 22:00',
                    'order': 0,
                    'day_x': 0,
                    'spot_time': None
                    },
                {
                    'kor_name': '본전돼지국밥',
                    'eng_name': 'Bonjeon Pork Soup',
                    'description': '부산의 전통적인 돼지국밥 전문점으로, 깊고 진한 국물과 신선한 재료로 만든 국밥이 인기입니다.',
                    'address': '부산 동구 중앙대로214번길 3-8',
                    'url': 'https://www.example.com',
                    'image_url': 'https://www.visitbusan.net/uploadImgs/files/cntnts/20191220093930814_oen',
                    'map_url': 'https://map.kakao.com/link/map/12478775',
                    'latitude': 35.1165795385369,
                    'longitude': 129.041386778583,
                    'spot_category': 2,
                    'phone_number': '051-441-2946',
                    'business_status': True,
                    'business_hours': '매일 10:00 ~ 22:00',
                    'order': 0,
                    'day_x': 0,
                    'spot_time': None
                },
                {
                    'kor_name': '미청식당',
                    'eng_name': 'Micheong Restaurant',
                    'description': '부산의 인기 맛집으로, 다양한 메뉴를 제공하며, 가족 단위 방문에 적합합니다.',
                    'address': '부산 기장군 일광읍 기장해안로 1303',
                    'url': 'https://www.example.com',
                    'image_url': 'https://image.linktoplace.com/20220704/d41d8cd98f00b204e9800998ecf8427e/98b104163be1a79278dec788e58473d9.jpg',
                    'map_url': 'https://map.kakao.com/link/map/11062140',
                    'latitude': 35.26025007652379,
                    'longitude': 129.23317177820252,
                    'spot_category': 2,
                    'phone_number': '051-721-7050',
                    'business_status': True,
                    'business_hours': '매일 10:00 ~ 21:00',
                    'order': 0,
                    'day_x': 0,
                    'spot_time': None
                },
                {
                    'kor_name': '해운대 기와집 대구탕',
                    'eng_name': 'Haeundae Giyang House Daegu Soup',
                    'description': '해운대 해수욕장과 광안대교가 내려다보이는 기와집에서 대구탕을 전문으로 하는 식당입니다. 푸짐한 대구와 맑은 국물로 시원한 맛을 자랑하며, 가족 단위 방문에 적합합니다.',
                    'address': '부산 해운대구 달맞이길104번길 46',
                    'url': 'https://korean.visitkorea.or.kr/detail/ms_detail.do?cotid=3b85f5a2-0348-4981-9e01-a2b79ace8f31',
                    'image_url': 'https://fastly.4sqi.net/img/general/600x600/2125477_KWmUQDUkgdK4BAl1aF7N_3-D9JXixRqi3E8foQkZje0.jpg',
                    'map_url': 'https://map.kakao.com/link/map/8616462',
                    'latitude': 35.15816692361459,
                    'longitude': 129.17452687613843,
                    'spot_category': 2,
                    'phone_number': '051-731-5020',
                    'business_status': True,
                    'business_hours': '매일 10:00 ~ 21:00',
                    'order': 0,
                    'day_x': 0,
                    'spot_time': None
                },
                {
                    'kor_name': '할매재첩국',
                    'eng_name': 'Halmae Jeongol',
                    'description': '부산의 전통적인 재첩국 전문점으로, 깊고 진한 국물과 신선한 재첩이 특징입니다. 현지인들에게 사랑받는 맛집입니다.',
                    'address': '부산 수영구 광남로120번길 8',
                    'url': 'https://www.example.com',
                    'image_url': 'https://i3.ruliweb.com/img/19/08/24/16cc2dd714b4149a7.jpg',
                    'map_url': 'https://map.kakao.com/link/map/8154162',
                    'latitude': 35.15188045883426,
                    'longitude': 129.11638993345235,
                    'spot_category': 2,
                    'phone_number': '051-751-7658',
                    'business_status': True,
                    'business_hours': '매일 10:00 ~ 22:00',
                    'order': 0,
                    'day_x': 0,
                    'spot_time': None
                },
                {
                    'kor_name': '이재모피자 본점',
                    'eng_name': 'Lee Jaemo Pizza Main Store',
                    'description': '부산의 인기 피자 전문점으로, 다양한 종류의 피자를 제공합니다. 아늑한 분위기에서 식사를 즐길 수 있습니다.',
                    'address': '부산 중구 광복중앙로 31',
                    'url': 'https://www.example.com',
                    'image_url': 'https://img-cdn.theqoo.net/ISssZD.jpg',
                    'map_url': 'https://map.kakao.com/link/map/10070964',
                    'latitude': 35.10204215079571,
                    'longitude': 129.030747190728,
                    'spot_category': 2,
                    'phone_number': '051-255-9494',
                    'business_status': True,
                    'business_hours': '매일 11:00 ~ 22:00',
                    'order': 0,
                    'day_x': 0,
                    'spot_time': None
                },
                {
                    'kor_name': '신발원',
                    'eng_name': 'Sinbalwon',
                    'description': '부산역 근처에 위치한 중국식 만두 전문점으로, 육즙이 가득한 만두가 인기입니다. 깔끔한 인테리어와 친절한 서비스로 가족 단위 방문에 적합합니다.',
                    'address': '부산 동구 대영로243번길 62',
                    'url': 'https://www.siksinhot.com/P/24962',
                    'image_url': 'https://d2u3dcdbebyaiu.cloudfront.net/uploads/atch_img/36/eaab2cf081a275b9313c7405702cc88c_res.jpeg',
                    'map_url': 'https://map.kakao.com/link/map/8407645',
                    'latitude': 35.11481502493382,
                    'longitude': 129.03871169461524,
                    'spot_category': 2,
                    'phone_number': '051-467-0177',
                    'business_status': True,
                    'business_hours': '매일 11:00 ~ 20:30',
                    'order': 0,
                    'day_x': 0,
                    'spot_time': None
                },
                {
                    'kor_name': '개미집 서면1번가직영점',
                    'eng_name': 'Gaemijip Seomyeon 1st Street Direct Store',
                    'description': '부산의 인기 맛집으로, 다양한 메뉴를 제공하며, 가족 단위 방문에 적합합니다.',
                    'address': '부산 부산진구 신천대로62번길 73',
                    'url': 'https://www.example.com',
                    'image_url': 'https://d2uja84sd90jmv.cloudfront.net/posts/2VpoWxRTR-tjQdVv9ZSzQA/ms.jpg',
                    'map_url': 'https://map.kakao.com/link/map/8738686',
                    'latitude': 35.1540384459567,
                    'longitude': 129.058263303059,
                    'spot_category': 2,
                    'phone_number': '051-819-8809',
                    'business_status': True,
                    'business_hours': '매일 10:00 ~ 21:00',
                    'order': 0,
                    'day_x': 0,
                    'spot_time': None
                }
            ]
        },
    'site': [
       {
            'placeId': '부산광역시 -  부산광역시 해운대 해수욕장',
            'kor_name': '해운대 해수욕장',
            'eng_name': None,
            'address': '부산광역시 해운대구 해운대해변로 140',
            'url': None,
            'image_url': 'http://imgnews.naver.net/image/032/2020/08/20/0003027691_001_20200820152808750.jpg',
            'map_url': 'https://map.example.com/haeundae',
            'latitude': 35.1587,
            'longitude': 129.1604,
            'spot_category': 1,
            'phone_number': None,
            'business_status': None,
            'business_hours': None,
            'day': 1,
            'order': 1
        }, 
        {
            'placeId': '부산광역시 -  부산광역시 광안리  해수욕장',
            'kor_name': '광안리 해수욕장',
            'eng_name': None,
            'address': '부산광역시 수영구 광안해변로 219',
            'url': None,
            'image_url': 'https://png.pngtree.com/thumb_back/fw800/background/20230322/pngtree-gwangalli-beach-in-busan-photo-image_2097801.jpg',
            'map_url': 'https://map.example.com/gwangalli',
            'latitude': 35.1533,
            'longitude': 129.1181,
            'spot_category': 1,
            'phone_number': None,
            'business_status': None,
            'business_hours': None,
            'day': 1,
            'order': 2
        },
        {
            'placeId': '부산광역시 -  부산광역시 부산타워',
            'kor_name': '부산타워',
            'eng_name': None,
            'address': '부산광역시 중구 용두산길 37',
            'url': None,
            'image_url': 'https://i1.ruliweb.com/img/17/07/09/15d2615b0c61431b.jpg',
            'map_url': 'https://map.example.com/busan_tower',
            'latitude': 35.0976,
            'longitude': 129.0335,
            'spot_category': 1,
            'phone_number': None,
            'business_status': None,
            'business_hours':None,
            'day': 1,
            'order': 3
        },
        {
            'placeId': '부산광역시 -  부산광역시 감천문화마을',
            'kor_name': '감천문화마을',
            'eng_name': None,
            'address': '부산광역시 사하구 감천로 203',
            'url': None, 'image_url': 'https://i.pinimg.com/736x/a2/44/fe/a244fed57bf0408c6149ac9519b86203.jpg',
            'map_url': 'https://map.example.com/gamcheon',
            'latitude': 35.0973,
            'longitude': 129.0101,
            'spot_category': 1,
            'phone_number': None,
            'business_status': None,
            'business_hours': None,
            'day': 2,
            'order': 1
        },
        {
            'placeId': '부산광역시 - 부산광역시 부산국제영화제',
            'kor_name': '부산국제영화제',
            'eng_name': None,
            'address': '부산광역시 해운대구 센텀남대로 30',
            'url': None,
            'image_url': 'http://imgnews.naver.net/image/001/2011/09/08/PYH2011081606020005100_P2.jpg',
            'map_url': 'https://map.example.com/biff',
            'latitude': 35.1692,
            'longitude': 129.1295,
            'spot_category': 1,
            'phone_number':None, 
            'business_status': None, 
            'business_hours': None, 
            'day': 2, 
            'order': 2
        }, 
        {
            'placeId': '부산광역시 -  부산광역시 동백섬',
            'kor_name': '동백섬', 
            'eng_name': None, 
            'address': '부산광역시 해운대구 동백로 1',
            'url': None,
            'image_url': 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Dongbaek_Island_20200522_016.jpg',
            'map_url': 'https://map.example.com/dongbaek',
            'latitude': 35.1530,
            'longitude': 129.1534,
            'spot_category': 1,
            'phone_number': None,
            'business_status': None,
            'business_hours': None,
            'day': 2,
            'order': 3
        }
    ],
    'cafe':  
        {'spots':[
            {
                'kor_name': '어거스타',
                'eng_name': 'Augusta',
                'description': '조용하고 아늑한 분위기에서 클래식한 케이크와 커피를 즐길 수 있는 카페입니다. 특히 딸기 생크림 케이크가 인기입니다. 30대 고객들에게 적합한 편안한 공간으로, 친구들과의 대화나 혼자서 책을 읽기 좋은 장소입니다.',
                'address': '부산광역시 수영구 무학로33번길 43 2층',
                'url': 'https://www.instagram.com/augusta_coffee',
                'image_url': 'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20241127_294%2F1732680581936FlN9g_JPEG%2F0W9A5219.jpeg',
                'map_url': 'https://map.kakao.com/link/map/35.1633609,129.1177618',
                'latitude': 35.1633609,
                'longitude': 129.1177618,
                'spot_category': 3,
                'phone_number': '0507-1354-0396',
                'business_status': True,
                'business_hours': '11시 0분에 영업 시작',
                'order': 1,
                'day_x': 1,
                'spot_time': '11:00'
            },
            {
                'kor_name': '타고커피 해리단길',
                'eng_name': 'Tago Coffee Harrydan-gil',
                'description': '아기자기한 인테리어와 고소한 음료가 매력적인 카페입니다. 넛티브라운라떼와 찰떡플이 특히 인기 있으며, 친구들과의 모임에 적합합니다. 30대 고객들이 선호하는 분위기로, 소셜 미디어에 올리기 좋은 포토존이 많습니다.',
                'address': '부산광역시 해운대구 우동1로 42 2층 타고커피 해리단길',
                'url': 'https://www.instagram.com/tago.coffee__',
                'image_url': 'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20230609_86%2F1686297807146AlD5v_JPEG%2F23F80CDB-AFC0-46DA-8439-9FDCB386823A.jpeg',
                'map_url': 'https://map.kakao.com/link/map/35.1651752,129.1577018',
                'latitude': 35.1651752,
                'longitude': 129.1577018,
                'spot_category': 3,
                'phone_number': '0507-1315-2140',
                'business_status': True,
                'business_hours': '11시 0분에 영업 시작',
                'order': 2,
                'day_x': 1,
                'spot_time': '12:00'
            },
            {
                'kor_name': '테라로사 수영점',
                'eng_name': 'Terarosa Suyeong',
                'description': '부산에서 가장 맛있는 커피를 자랑하는 카페로, 핸드드립 커피와 피칸파이가 인기입니다. 조용한 분위기에서 데이트하기 좋은 장소입니다. 30대 고객들이 선호하는 고급스러운 커피 경험을 제공합니다.',
                'address': '부산광역시 수영구 구락로123번길 20 F1963',
                'url': 'https://terarosa.com',
                'image_url': 'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20200420_9%2F1587356087804N3UR5_JPEG%2FZPNEW1_Fd7tJ4aAL536QYBJe.JPG.jpg',
                'map_url': 'https://map.kakao.com/link/map/35.1770726,129.1148806',
                'latitude': 35.1770726,
                'longitude': 129.1148806,
                'spot_category': 3,
                'phone_number': '1668-2764',
                'business_status': True,
                'business_hours': '20시 30분에 라스트오더',
                'order': 3,
                'day_x': 1,
                'spot_time': '14:00'
            },
            {
                'kor_name': '압트커피',
                'eng_name': 'Apt Coffee',
                'description': '디저트와 커피가 모두 맛있는 카페로, 특히 딸기케이크와 초코케이크가 인기입니다. 아늑한 분위기에서 대화하기 좋은 장소입니다. 30대 고객들이 편안하게 대화할 수 있는 공간으로 인기가 높습니다.',
                'address': '부산광역시 부산진구 전포대로 226-8 2층',
                'url': 'https://www.instagram.com/aptcoffee.busan',
                'image_url': 'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20241128_75%2F1732791254251lkOvl_JPEG%2F2537994B-EDC6-47A1-B2FF-8B6733E9138F.jpeg',
                'map_url': 'https://map.kakao.com/link/map/35.1568768,129.0658061',
                'latitude': 35.1568768,
                'longitude': 129.0658061,
                'spot_category': 3,
                'phone_number': '0507-1495-9926',
                'business_status': True,
                'business_hours': '21시 0분에 영업 종료',
                'order': 4,
                'day_x': 1, 
                'spot_time': '16:00'
            },
            {
                'kor_name': '쿠모네스트',
                'eng_name': 'Kumonest',
                'description': '아늑한 분위기와 친절한 서비스가 매력적인 카페입니다. 핸드드립 커피와 디저트가 잘 어우러져 있습니다. 30대 고객들이 편안하게 쉴 수 있는 공간으로, 조용한 대화나 작업에 적합합니다.',
                'address': '부산광역시 남구 지게골로 101-4 쿠모',
                'url': 'https://www.instagram.com/kumonest_coffee?igsh=bXV0NGIxNHAzcjZp&utm_source=qr',
                'image_url': 'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20240730_103%2F1722273899466kkKpn_JPEG%2FD0F8D791-2667-49EB-8C43-3E9391A51B5B.jpeg',
                'map_url': 'https://map.kakao.com/link/map/35.1350658,129.0734299',
                'latitude': 35.1350658,
                'longitude': 129.0734299,
                'spot_category': 3,
                'phone_number': '0507-1382-2280',
                'business_status': True,
                'business_hours': '11시 30분에 영업 시작',
                'order': 5,
                'day_x': 1, 
                'spot_time': '18:00'
            },
            {
                'kor_name': '우당탕 커피스토리',
                'eng_name': 'Woos Coffee Story',
                'description': '감각적인 인테리어와 맛있는 케이크가 매력적인 카페입니다. 특히 딸기 초코 케이크와 얼그레이 케이크가 인기입니다. 30대 고객들이 좋아하는 트렌디한 분위기로, 친구들과의 모임에 적합합니다.',
                'address': '부산광역시 수영구 연수로392번길 52 1층 우당탕 커피스토리',
                'url': 'https://smartstore.naver.com/woocus',
                'image_url': 'https://search.pstatic.net/common/?autoRotate=true&type=w560_sharpen&src=https%3A%2F%2Fldb-phinf.pstatic.net%2F20240716_294%2F1721117433539y1JPu_JPEG%2FR0084233.JPG',
                'map_url': 'https://map.kakao.com/link/map/35.167521,129.1104733',
                'latitude': 35.167521,
                'longitude': 129.1104733,
                'spot_category': 3,
                'phone_number': '0507-1321-7484',
                'business_status': True,
                'business_hours': '13시 0분에 영업 시작',
                'order': 6,
                'day_x': 1, 
                'spot_time': '20:00'
            }
        ]
    },    
    'accommodation': [
        {
            'kor_name': '호텔 노스하버',
            'eng_name': 'Hotel North Harbor',
            'description': '체크인 오후 3:00, 체크아웃 오전 11:00, 유아 동반 환영, 무료 Wi-Fi',
            'address': '부산광역시 영도구 대교동1가 태종로 45 안내데스크  8층',
            'url': 'https://www.google.com/travel/search?q=호텔%20노스하버',
            'image_url': 'https://lh5.googleusercontent.com/p/AF1QipPRNRIvQcsBArjjuZNU-UGvTmenSewZCtd2vGK5=s287-w287-h192-n-k-no-v1',
            'map_url': 'https://www.google.com/maps?q=35.0939236,129.0373082',
            'latitude': 35.0939236,
            'longitude': 129.0373082,
            'spot_category': 0,
            'phone_number': None,
            'business_status': None,
            'business_hours': None,
            'order': 1,
            'day_x': 0,
            'spot_time': '22:00:00'
        },
        {
            'kor_name': '스테이 가온',
            'eng_name': 'Stay Gaon', 
            'description': '체크인 오후 4:00, 체크아웃 오전 11:00, 유아 동반 환영, 무료 Wi-Fi', 
            'address': '부산광역시 중구 중앙대로 24',
            'url': 'https://www.google.com/travel/search?q=스테이%20가온',
            'image_url': 'https://lh5.googleusercontent.com/p/AF1QipNedYx1HPkzEiuqqIciXeOl7FPg-VC2gyRVBbnF=s287-w287-h192-n-k-no-v1',
            'map_url': 'https://www.google.com/maps?q=35.0997435,129.0368834', 
            'latitude': 35.0997435,
            'longitude': 129.0368834, 
            'spot_category': 0, 
            'phone_number': None, 
            'business_status': None, 
            'business_hours': None, 
            'order': 2,
            'day_x': 0, 
            'spot_time': '22:00:00'
        }, 
        {
            'kor_name': '베이하운드호텔',
            'eng_name': 'Bayhound Hotel',
            'description': '체크인 오후 3:00, 체크아웃 오전 11:00, 유아 동반 환영, 무료 Wi-Fi',
            'address': '부산광역시 영도구 태종로65번길 11',
            'url': 'https://www.google.com/travel/search?q=베이하운드호텔',
            'image_url': 'https://lh5.googleusercontent.com/p/AF1QipN0IHDIbI44iQ7e7uFm_8MB7IAIc5azfnI-tQN3=s287-w287-h192-n-k-no-v1',
            'map_url': 'https://www.google.com/maps?q=35.0931507,129.0384545',
            'latitude': 35.0931507,
            'longitude': 129.0384545,
            'spot_category': 0,
            'phone_number': None,
            'business_status': None,
            'business_hours': None,
            'order': 3,
            'day_x': 0,
            'spot_time': '22:00:00'
        },
        {
            'kor_name': '브로시스호텔',
            'eng_name': 'Brosys Hotel',
            'description': '체크인 오후 4:00, 체크아웃 오후 12:00, 유아 동반 환영, 무료 Wi-Fi',
            'address': '부산광역시 중구 구덕로48번길 4',
            'url': 'https://www.google.com/travel/search?q=브로시스호텔',
            'image_url': 'https://lh5.googleusercontent.com/p/AF1QipN8-QMpYtzZdjcwL2mbyfMamF4Zu7LoAdPY7s1F=s287-w287-h192-n-k-no-v1',
            'map_url': 'https://www.google.com/maps?q=35.0985983,129.0309031',
            'latitude': 35.0985983,
            'longitude': 129.0309031,
            'spot_category': 0,
            'phone_number': None,
            'business_status': None,
            'business_hours': None,
            'order': 4,
            'day_x': 0,
            'spot_time': '22:00:00'
        },
        {
            'kor_name': '호텔 더 루아 남포롯데점',
            'eng_name': 'Hotel The Lua Nampo Lotte',
            'description': '체크인 오후 3:00, 체크아웃 오전 11:00, 유아 동반 환영, 무료 Wi-Fi',
            'address': '부산광역시 중구 대청로134번길 23',
            'url': 'https://www.google.com/travel/search?q=호텔%20더%20루아%20남포롯데점',
            'image_url': 'https://lh5.googleusercontent.com/p/AF1QipOD9ZmuAjzuMkIOcYOsVQSzAtUkOvSt0gKLfnOe=s287-w287-h192-n-k-no-v1',
            'map_url': 'https://www.google.com/maps?q=35.1008313,129.0353097',
            'latitude': 35.1008313,
            'longitude': 129.0353097,
            'spot_category': 0,
            'phone_number': None,
            'business_status': None,
            'business_hours': None, 
            'order': 5, 
            'day_x': 0, 
            'spot_time': '22:00:00'
        }
    ]
}
